### ISSUE TITLE
Fix ground truth data for prepare_opensfm test

### ISSUE THREAD

**Issue by LukasBommes** [LukasBommes/PV-Hawk#20]
With undistort=False ground truth data for the prepare_opensfm test if now incorrect. Update ground truth data to fix that.

**Comment by riham-basheer** [comment]
I second this. Thanks for the heads up.

If you are having the error message:
FAIL: test run (tests.integration.test prepare opensfm.Test Prepare Opensfm) ---------------------------------------------------------------------- Traceback (most recent call last): File "/pvextractor/tests/integration/test_prepare_opensfm.py", line 61, in test_run os.path.join(self.ground_truth_dir, "cluster_000000", "images") AssertionError: False is not true

Go to : PV-Hawk/extractor/mapping/prepare_opensfm.py
And turn any undistort=False to True.

**Comment by riham-basheer** [comment]
I second this. Thanks for the heads up.

If you are having the error message:
FAIL: test run (tests.integration.test prepare opensfm.Test Prepare Opensfm) ---------------------------------------------------------------------- Traceback (most recent call last): File "/pvextractor/tests/integration/test_prepare_opensfm.py", line 61, in test_run os.path.join(self.ground_truth_dir, "cluster_000000", "images") AssertionError: False is not true

Go to : PV-Hawk/extractor/mapping/prepare_opensfm.py
And turn any undistort=False to True.
